### ISSUE TITLE
osmscout-server on Pinephone fails after SIGILL

### ISSUE THREAD

**Issue by RapidRotator** [rinigus/osmscout-server#394] opened 2022-01-15 18:37 UTC
I installed osmscout-server and pure-maps on my Pinephone with PostmarketOS using:

`$ apk add osmscout-server pure-maps`

The Pinephone has 3GB RAM

Initially subscribing to maps and downloading them took a while but went without problem, but since then osmscout-server fails after a lot of missing data warnings and finally a SIGILL Illegal instruction)

[stdout.log](https://github.com/rinigus/osmscout-server/files/7875615/stdout.log)

**Comment by rinigus** [comment] 2022-01-15 18:43
I forgot, it looks like this is duplicate of #345

**Closed** 2022-01-15 18:43 UTC
