### ISSUE TITLE
Allow stylesheet to be specified by the client

### ISSUE THREAD

**Issue by Thra11** [rinigus/osmscout-server#150] opened 2017-06-07 17:35 UTC
Similar to how the client can request day or night tiles, it would be useful if the client could specify the stylesheet used. This would mean that the user could switch layers in poor maps between e.g. a cycle map, a public transport map and a normal map.

It would also mean that the client can cache cycle map tiles and transport tiles in separate caches, whereas if the stylesheet is switched in the server settings, the client is unaware that the cached tiles don't match.

I don't know if this would cause problems by making the query API different to the OSM convention. If this is problem, perhaps the stylesheet could use a different route, i.e. http://localhost:8553/v1/cycle/tile?...

**Comment by rinigus** [comment] 2017-06-07 18:47
Its a great idea! Thank you for proposing it!

URL syntax is very easy to expand by adding additional option:

`http://localhost:8553/v1/tile?`**style={style}**`&daylight={dlight}&shift={shift}&scale={scale}&z={z}&x={x}&y={y}`

`style` could be cycle, transport, default, car, ...

Style would have to be defined on the server side (like `mapnik.xml`, but different files for different styles).

Then, in Poor Maps / modRana, we could make the corresponding providers. Possibly we could ask clients to change daylight settings automatically leading to the reduction of user-specified options. And, indeed, the caches would be separate.

There are great advantages in making separate styles. Right now I was always looking for compromises trying to combine different priorities. With the different styles, it would be simple to stress the corresponding options. For example, cycle and public transport maps would probably be much better for corresponding use. 

Now, the problem is that we don't have all these styles. So, those would have to be designed as well. I guess, as soon as we have them it would be really easy to implement this idea.

Now a question: Which backend are we talking about, Mapnik? While I mainly use Mapnik these days, I don't know much about the others and their preferences. Hence the question.

Since I was working on Mapnik style recently, I do remember the syntax and places where I would have to change things. I guess, at this stage, we could first figure out which styles would be needed, how to show data by zoom layers, select colors for the features, and later implement that. Implementation is not difficult as soon as the rest is known :) . With libosmscout styles I am not that familiar at this stage...

**Comment by Thra11** [comment] 2017-06-09 18:57
It looks like neither the opencyclemap layer nor the public transport layer on openstreetmap.org publish their stylesheets. There are various stylesheets shared on github and elsewhere, but most seem to be just variations on normal/multi-purpose maps rather than more focussed maps like cycle or public transport. So it does look like we might have to develop our own stylesheets before this feature can be really useful.

Ideally, the style option would be backend-agnostic, although of course we do have the same issue with libosmscout as with mapnik in that we don't have many different stylesheets available at the moment.

Another question is how the client knows which styles the server offers. Do we offer a finite number of pre-defined tags (e.g. normal, cycle, transport) which can then be hard-coded in providers in poor maps and so on? If so, do you think we should aim to bundle stylesheets with osm-scout-server for every tag, or should we try to make it so that the user can install third party stylesheets, then match them with a style tag in osm scout server's settings?

I haven't worked with mapnik styles for a long time (and I've never worked with libosmscout styles at all), so I will go and study/revise mapnik xml syntax.

**Comment by Thra11** [comment] 2017-06-09 19:09
Not strictly related to this feature request, but the opencyclemap tiles use SRTM data to render contours, which I assume isn't currently available in osm-scout-server (and might take up too much disk space to be worthwhile). Details [here](https://wiki.openstreetmap.org/wiki/Contours). I believe 'hill shading' also has similar requirements.

**Comment by rinigus** [comment] 2017-06-09 20:27
**Re backends**: I would suggest to focus on Mapnik at present. The quality of rendering is much better. There is a progress with libosmscout rendering, but it would take some time before it will catch up, I think. Since we do have limited resources, its probably better to focus on something and try to make it as good as we can. As for styles, I don't think its an issue to "translate" them between backends when libosmscout rendering will catch up. 

**Re mapnik style**: I am using CartoCSS based style https://github.com/rinigus/mapnik-styles-sqlite . In the end, it turned a bit complicated. I tried to match the layers on the map ( https://github.com/rinigus/mapnik-styles-sqlite/blob/master/osm-bright/osm-bright.spatialite.mml ) with the tables in SQLite database ( https://github.com/rinigus/mapnik-styles-sqlite/blob/master/importer/reorganize.sql ). I think it should lead to better performance on the device, but it means that its harder to grasp all parts immediately. 

Style can be developed using some completely different editors as well, such as Mapbox Studio. If its mainly changing colors when compared to the current style, I can easily adopt it. With this editor (and few other options) we should be very careful with the license of the style used as a base. Mapbox Street and few others are specifically to be used with their products. So, we cannot just copy those.

So, regarding technical part of developing styles: I am trying to say that if you feel more comfortable using some other tool in developing it, I would be happy to try to "translate" it to Mapnik/CartoCSS and generate XML from it.

**Re client interaction**: Taking into account client's architecture, for them its easiest if we offer preset tags in front. Then expanding client with the styles is simple.

**Re distribution**: I don't know. Currently, since Mapnik supports only one style (no daylight settings), user can choose any folder with the file mapnik.xml  and use that style. If we go for different tags, I presume it will be some tree of folders, each corresponding to daylight/tag setting. I have no idea how many styles would start to circulate around, so far you are the first who is actually actively thinking about it and expressing the opinion. We could start with bundling styles with the server and, if it becomes popular, just add GUI option allowing you to select the new styles bundle. Or go for modules. I guess, as soon as we see how it evolves, we will adapt. 

**Re contours**: We can surely look into it. In theory, it should be not too bad, but maybe we'll see how we can develop simpler styles first.

**Re on options**: We should be careful and keep things as simple as possible. It looks that already current setup (server + Poor Maps/modRana) is a great challenge for several users to grasp. If we start adding options for all kind of styles, we may get support headache on our hands in no time. Ideally, it should just starting the server and, after small initial configuration, forgetting it on the background. There will be few things that you would have to do on the server (manage maps, change parsing language while you travel), but would be great to keep it simple.

**Comment by rinigus** [comment] 2017-06-28 20:22
We should have working mechanism now for supporting different styles in Mapnik. I have adopted a night style (will soon update screenshots) and scripts to support multiple styles in https://github.com/rinigus/mapnik-styles-sqlite . Now we just miss the styles ... I am planning to make a car style and move few things in the default one.

**Comment by rinigus** [comment] 2017-06-29 17:32
As such, the style is now possible to specify by the client. I am going to close the issue since its implemented now. But that shouldn't stop us discussing it [if needed] here or in some other place.

**Closed by rinigus** 2017-06-29 17:32 UTC
