### ISSUE TITLE
Unable to open main menu since OTA-23

### ISSUE THREAD

**Issue by stanwood77** [rinigus/osmscout-server#404] opened 2022-07-03 14:36 UTC
Since OTA-23 release, it seams that the app is partially broken.

One can not open the main menu (3 little line on the left top main screen) anymore. The icon just doesn't react t all.

This behaviour is confirmed on Vollaphone Stable channel. No log to provide at this stage.

Other users are reporting facing the same issues on various device: https://forums.ubports.com/topic/7821/osm-scout-server-improvements/8

Thank you very much for your support.

Regards, Steve

**Comment by rinigus** [comment] 2022-07-03 15:11
@jonnius: Is it something similar to what we had/have in Pure Maps?

**Comment by zubozrout** [comment] 2022-07-03 16:52
Isn't this a duplicate of https://github.com/rinigus/osmscout-server/issues/396?

**Comment by stanwood77** [comment] 2022-07-03 17:42
Maybe related, but not duplicated, as this menu was working a few weeks ago as I remembered on Ubuntu Touch.

**Comment by rinigus** [comment] 2022-07-03 17:46
Is probably related: https://github.com/rinigus/osmscout-server/pull/402

**Comment by petroniusniger** [comment] 2022-07-04 13:36
Just to confirm that I noticed this problem as well:
- Xiaomi Mi A2
- OTA-23
- OSM Scout Server 2.2.0

Log messages in attached picture:
![screenshot20220704_153258804_small](https://user-images.githubusercontent.com/7203946/177165959-09728052-ac71-47e0-b4d1-eda804e6c0b1.jpg)

**Comment by jonnius** [comment] 2022-07-06 06:41
@rinigus, yes, it seems it is time to merge #402 and ship it as soon as possible.

**Comment by rinigus** [comment] 2022-07-06 17:31
Corresponding PR has been merged. Please let me know if it is fixed in the next server release and whether we can close this issue

**Comment by rinigus** [comment] 2022-07-07 17:37
According to the feedback from @jonnius , this is fixed. Closing

**Closed by rinigus** 2022-07-07 17:37 UTC
