### ISSUE TITLE
(Sailfish) Search near current/last gps position by default

### ISSUE THREAD

**Issue by savegame** [rinigus/osmscout-server#317] opened 2019-10-08 18:12 UTC
When i try search something in PureMaps using OSMScout, its show much unusable results, even it to far (~2000km and more), like some streets in other cities, but i have same streets names near to my current geo position.

**Comment by rinigus** [comment] 2019-10-08 18:48
Fair enough. OSM Scout Server (or to be more specific, its geocoder) doesn't arrange results according to the distance from the current location. Pure Maps has now support for it while querying geocoders  and this is planned for the server as well.

Closing here as a duplicate of #312

**Closed by rinigus** 2019-10-08 18:48 UTC
