### ISSUE TITLE
SEVERAL ISSUE in RENDER and ADDRESS-POI LOOK UP

### ISSUE THREAD

**Issue by Caballlero** [rinigus/osmscout-server#109] opened 2017-04-09 01:42 UTC
HI rinigus 
 v-o.8.1
i want to know why your app not extract all information provided in the maps, example if i search something in modrana in search -place it is a little information i get most time anything. also i have 2 maps downloaded -guatemala-georgia,usa and the guatemala maps is my main map ,then i have several problem to rendering my country ,the other map like georgia,usa it is ok in render. exept to poor information  when a search something in modrana-search-place. your maps look great compared to karry maps ,but karry maps when i search somethig it is give me a FULL information IF AVAILABLE ON MAP. ,i would like karry search in your app rinigus ,Although I do not know who is the problem of extracting information available on the map if modrana oh osmscout-server. i hope so you hear as well .thanks : (

**Comment by rinigus** [comment] 2017-04-09 04:17
Hi,

please provide specific examples.When reporting issues on search, please  also specify whether you use geocoder-nlp or libosmscout for search. If you use libosmscout then please try geocoder-nlp search as well. For reoorts on rendering , it would help to see examples as well.

**Comment by rinigus** [comment] 2017-04-09 04:35
and thank you for report , let's see how to fix it... So, please give examples.

**Comment by Caballlero** [comment] 2017-04-09 16:35
hello rinigus
- with geocoder-nlp or with libosmscout-server it is the same i can not search anything  on my country.
EXAMPLE WITH KARRY-APP VIEW
![20170409122330](https://cloud.githubusercontent.com/assets/24536606/24838994/b06a7120-1d20-11e7-8ccf-2acbd02b92b3.jpg)
 HERE RINIGUS-APP
![20170409122828](https://cloud.githubusercontent.com/assets/24536606/24838999/c7c3ff58-1d20-11e7-8eff-8f6428fa0265.jpg)
-is disfigured, and if I move away it disappears completely instead of changing size, which does not happen with the other map.

**Comment by rinigus** [comment] 2017-04-09 16:56
I tried to search for McDonalds and that worked. Not too hard though. Maybe you could give some specific example? Try to search for it at openstreetmap.org and tell me the search string that you used. Note: you have to specify languages in geocoder-nlp settings , but you probably did it .

as for rendering  , we are working on it . it  seems to be fine when you zoom into country , like into some city . but this overall rendering is problematic . and there are some patches on which Lukas is working to solve it.

**Comment by Caballlero** [comment] 2017-04-09 17:05
how you search mcdonalds with modrana or osmscout-server-terminal? i have downloaded both  languages in geocoder-nlp [ES] [EN].

**Comment by rinigus** [comment] 2017-04-09 17:43
I used Poor Maps, but it should be the same as modRana. In Poor Maps, I selected Search, Using OSM Scout, typed McDonalds and pressed Enter. At that time, the server was running as an application. Search results were there. 

OK, I assumed that you were searching in Sailfish. In Sailfish, you are expected to download all modules through manager. Did you download somehow differently? Where did you get [en] and [es], as far as I know its a single package with all languages.

Can you paste the log of the server in response to your search? You could also make a screenshot from server's main window after search, for example. There is also logging section in settings that you could use for it.

**Comment by Caballlero** [comment] 2017-04-09 18:48
rinigus 
I solved the problem of searching, I had not selected the map of Guatemala ,i had selected the other map, for that  not given information. But on the rendering that is a problem that continues

**Comment by rinigus** [comment] 2017-04-09 20:00
Yes, rendering is an issue and there is work going on it.

**Comment by rinigus** [comment] 2017-04-22 14:12
This is fixed in upcoming release when using Mapnik backend. For libosmscout, the issue is probably not fully fixed yet. Closing it as a server issue since there is a solution that fixes it.

**Closed by rinigus** 2017-04-22 14:12 UTC
