### ISSUE TITLE
Error 500: unknown command when routing

### ISSUE THREAD

**Issue by otsaloma** [rinigus/osmscout-server#32] opened 2016-10-30 17:45 UTC
Output from Poor Maps:

```
Requesting http://localhost:8553/v1/route?type=car&p[0][search]=Helsinki&p[1][lng]=24.811749&p[1][lat]=60.218380
Requesting http://localhost:8553/v1/route?type=car&p[0][search]=Helsinki&p[1][lng]=24.811749&p[1][lat]=60.218380
Establishing connection to localhost:8553
Failed to download data: Exception: Server responded 500: 'unknown command'
Routing failed:
Traceback (most recent call last):
  File "/home/nemo/Source/poor-maps-osmscout/poor/router.py", line 89, in route
    return self._provider.route(fm, to, params)
  File "/home/nemo/Source/poor-maps-osmscout/routers/osmscout.py", line 68, in route
    result = poor.http.request_json(url)
  File "/home/nemo/Source/poor-maps-osmscout/poor/http.py", line 128, in request_json
    text = request_url(url, encoding, retry, headers)
  File "/home/nemo/Source/poor-maps-osmscout/poor/http.py", line 183, in request_url
    return request_url(url, encoding, retry-1, headers)
  File "/home/nemo/Source/poor-maps-osmscout/poor/http.py", line 165, in request_url
    repr(response.reason)))
Exception: Server responded 500: 'unknown command'
```

Poor Maps by default retries the same request once in cases of error. Hence, you see the request made twice and `Establishing connection` tells that a new connection was established for the retry.

Using Mapzen Metro Extract for the Helsinki region.

**Comment by rinigus** [comment] 2016-10-30 18:14
I can reproduce this as well! Thank you very much for detailed report.

**Comment by rinigus** [comment] 2016-11-11 21:54
I reported the issue to upstream and, it seems to me, its rather complicated case. The issue is discussed at https://github.com/Framstag/libosmscout/issues/153

As found by Tim, the road might be not reachable according to the map. In addition, I managed to get the case where, after recent upstream updates, I've got some very long (or maybe infinite) route calculations. Mapzen and MapQuest failed to calculate the route for my case (only OSRM managed to propose something). So, see upstream discussion and let us know if there are some errors in the map, for example.

**Comment by rinigus** [comment] 2016-11-13 15:09
Fixed at https://github.com/Framstag/libosmscout/issues/153 . Tested on Sailfish as well and it works nicely. If I pinpoint location on the north, it guides to the parking lot on the northern side, a bit further north over the railway. If we just specify the center, the southern entry is used.

Closing it here. Will be released as RPM with the next release.

**Closed** 2016-11-13 15:09 UTC
Labels: bug
