### ISSUE TITLE
App does not start when phone is not on network

### ISSUE THREAD

**Issue by RonnyB74** [rinigus/osmscout-server#411] opened 2022-11-14 17:27 UTC
Hello,

I have the problem that the program does not start when the network (WLAN or mobile data) is disabled. In the log, I get the following message:
`failed to start http server`
I have the problem on the Xperia 10-II and 10-III with SailfishOS 4.4.0.72. The version of osmscout-server is 2.2.0-1.6.1.
Is the problem known? Often in nature, you do not have a net. That's what the offline server is for, isn't it?
Thanks, Ronny

**Comment by rinigus** [comment] 2022-11-14 18:37
:) . The issue looks to be from systemd automatic activation. Try to disable "Automatic start" and in the server and try again. You would have to start it by launching the app, though.

**Comment by RonnyB74** [comment] 2022-11-19 16:41
If the automatic start is disabled, the server application can be started. Unfortunately, still no map tiles are loaded. Only when I activate the WLAN on the phone, the maps are also loaded. Something is still going wrong.

**Comment by rinigus** [comment] 2022-11-19 16:45
The maps not loading - that's old Qt bug that I forgot to take into account when publishing latest Maplibre GL release. That is only on SFOS and I would have to fix it.

**Comment by rinigus** [comment] 2022-11-20 09:37
Just looked through the code and I have applied the patch which we needed to access tiles. Tested on my device in "Flight" mode and couldn't reproduce your issue. My steps:

- start OSM Scout Server GUI
- switch to flight mode
- start Pure Maps with offline profile active
- I can browse maps, search as well
- In OSM Scout Server GUI, I can see queries for map tiles as well

**Comment by RonnyB74** [comment] 2022-12-11 17:21
Hello rinigus,

first of all thank you for your answer!

I have now tested with Pure Maps. Correct, here the map is also loaded offline.

So my problem is only in OSM Scout. Here I have configured the access to the OSM Scout server manually via the file "online-tile-providers.json":

`http://localhost:8553/v1/tile?style=default&daylight=1&scale=3&z=%1&x=%2&y=%3`

This does not seem to work offline.

Do you have any idea if there is a way around this?

Thanks, Ronny

**Comment by rinigus** [comment] 2022-12-11 20:59
I suspect OSM Scout is using Qt for HTTP access. So, unless we upgrade SFOS Qt to newer versions, that's a problem which will stay.

**Comment by rinigus** [comment] 2024-02-24 19:13
Closing as it is not issue with the server

**Closed by rinigus** 2024-02-24 19:13 UTC
